#ifndef PLATFORM_H
#define PLATFORM_H

#define PLTFRM_MICROBLAZE_CORE_CLOCK_FREQ_HZ 50*1000*1000
#define PLTFRM_MICROBLAZE_INTERRUPT 0
#define PLTFRM_MICROBLAZE_DATA_SIZE 32
#define PLTFRM_MICROBLAZE_IMEM_VOL 2*1024
#define PLTFRM_MICROBLAZE_DMEM_VOL 2*1024

#define PLTFRM_WBS_PIO 1
#define PLTFRM_WBS_PIO_BASEADDR 0x00010000
#define PLTFRM_WBS_PIO_HIGHADDR 0x00010FFF

#define PLTFRM_WBS_UART 1
#define PLTFRM_WBS_UART_BASEADDR 0x00011000
#define PLTFRM_WBS_UART_HIGHADDR 0x00011FFF
#define PLTFRM_WBS_UART_BAUDRATE 115200
#define PLTFRM_WBS_UART_DATA_BITS 8	/* 8 */
#define PLTFRM_WBS_UART_USE_PARITY 0	/* N */
#define PLTFRM_WBS_UART_STOP_BITS 1	/* 1 */

/* SYSTEM */
#define PLTFRM_SYS_STDIN_TYPE  PLTFRM_WBS_UART
#define PLTFRM_SYS_STDOUT_TYPE PLTFRM_WBS_UART


void init_platform();
void cleanup_platform();

#endif
